### ISSUE TITLE
Add test cases for data types supported

### ISSUE THREAD

**Issue by dongbohu** [greenelab/cimr#34]
The following test cases are needed:
* At least one test for each data type (`gwas`, `tad`, etc)
* At least one test for a downloaded tarball file that has one data type with at least two input data files
* At least one test for a downloaded tarball file whose data type is `multiple`, and each data type should include at least two input data files
 
The correctness of output files can be verified using either md5sum or `diff` command.

**Comment by ypar** [comment]
this has been resolved
