### ISSUE TITLE
Avoid duplicates output files

### ISSUE THREAD

**Issue by dongbohu** [greenelab/cimr#37]
Suppose the output file generated by `cimr` is going to be `data_type`/`file_name`. Before cimr starts writing this file, it should read `data_type` and `file_name` columns in `cimr-d_catalog.txt` to verify that a row of  `data_type` and `file_name` doesn't exist in `cimr-d_catalog.txt`. If such a row exists, `cimr` should report an error and stop immediately; otherwise the file generated will overwrite the file in `cimr-d` S3 bucket.

**Comment by ypar** [comment]
No. This would be a cimr-d feature, not cimr. I will transfer the issue.
